### PR TITLE
Remove Quest ID

### PR DESCRIPTION
**Pull request by Rhex-mod**
-remove quest id due to alot of string conflicts

### CODE REVIEW

**Comment by Eankun** [comment]
> -remove quest id due to alot of string conflicts

What conflicts are we talking about exactly?
If we're still talking about [Bm2], then I don't think we should remove all QIDs just because of that. Is there anything else?

**Comment by Rhex-mod** [comment]
well, there is also F13, F14 and F15 that shares the same quest title
and like u said, some other description might use the same text such as Operation A-gou

**Comment by Eankun** [comment]
Eh... Anyway, I think we won't remove quest IDs, since they're proved quite useful.
@Rhextian, can you please take all your new additions (new enemy vesels ets) to the new pull request. After that I just close this one.

**Comment by Rhex-mod** [comment]
@Eankun  done, waiting in pull up request
anyway, here is my organized version of the tr_data in case ur interested
https://github.com/Rhextian/Rhextian.github.io/blob/master/tr_data_kai.json

**Pull request closed without merging**
